set search_patch =cm;


-- TRIGGER
CREATE  TRIGGER TRG_PROPERTIES
    AFTER UPDATE ON PROPERTIES
    FOR EACH ROW EXECUTE PROCEDURE INSERT_PROPERTIES_VERSION();



 CREATE OR REPLACE FUNCTION  cm.INSERT_PROPERTIES_VERSION ()
 RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO PROPERTIES_VERSION(NAME,OLD_VALUE,NEW_VALUE,PROPERTY_FK)
    END;
  $$ LANGUAGE plpgsql;
